version: '3'
services:
  cg_users:
    container_name: cg_users
    env_file: .env
    build: .
    volumes:
      - .:/code
    ports:
      - "5000:5000"
    networks:
      - cg_users
    depends_on:
      - cg_users_postgres
    environment:
      - POSTGRES_NAME=cg_users_db
      - POSTGRES_PASSWORD=zapay
      - POSTGRES_USER=zapay
      - POSTGRES_HOST=cg_users_postgres
      - POSTGRES_PORT=5432
  cg_users_postgres:
    image: postgres:13
    container_name: cg_users_postgres
    ports:
      - "5432:5432"
    volumes:
      - ./.ignore/postgres:/var/lib/postgresql/data
    networks:
      - cg_users
    environment:
      - POSTGRES_NAME=cg_users_db
      - POSTGRES_PASSWORD=zapay
      - POSTGRES_USER=zapay
      - POSTGRES_DB=cg_users_db
  cg_users_pgadmin:
    profiles:  # Remove profiles if pgadmin is default
      - pgadmin
    image: dpage/pgadmin4
    container_name: cg_users_pgadmin
    networks:
      - cg_users
    ports:
      - "80:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=cg_users@usezapay.com.br
      - PGADMIN_DEFAULT_PASSWORD=zapay_pass
    volumes:
      - ./.ignore/pgadmin:/var/lib/pgadmin
networks:
  cg_users:
    driver: bridge
