# Generated by Django 4.0.4 on 2022-04-22 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Data na qual o objeto foi criada.', verbose_name='Data de criação')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Data na qual os dados do objeto foi atualizado no sistema.', verbose_name='Data de atualização')),
                ('deleted', models.BooleanField(default=False, help_text='Verifica se o objeto ainda está ativo no sistema.', verbose_name='Foi deletado?')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AddressModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Data na qual o objeto foi criada.', verbose_name='Data de criação')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Data na qual os dados do objeto foi atualizado no sistema.', verbose_name='Data de atualização')),
                ('deleted', models.BooleanField(default=False, help_text='Verifica se o objeto ainda está ativo no sistema.', verbose_name='Foi deletado?')),
                ('address', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('zip_code', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='users.usermodel')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
